# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ContifyAPI.Model.IndustriesGet200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :results
  ]

  @type t :: %__MODULE__{
          :results => [ContifyAPI.Model.GetTags.t()] | nil
        }
end

defimpl Poison.Decoder, for: ContifyAPI.Model.IndustriesGet200Response do
  import ContifyAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:results, :list, ContifyAPI.Model.GetTags, options)
  end
end
