# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ContifyAPI.Model.Attachment do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :source,
    :url
  ]

  @type t :: %__MODULE__{
          :source => String.t() | nil,
          :url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ContifyAPI.Model.Attachment do
  def decode(value, _options) do
    value
  end
end
