# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ContifyAPI.Model.CustomTopicResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :rule,
    :created_on,
    :updated_on
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t(),
          :rule => String.t() | nil,
          :created_on => String.t() | nil,
          :updated_on => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ContifyAPI.Model.CustomTopicResponse do
  def decode(value, _options) do
    value
  end
end
