# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ContifyAPI.Model.Duplicate do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :title,
    :summary,
    :url,
    :channel,
    :source
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :title => String.t() | nil,
          :summary => String.t() | nil,
          :url => String.t() | nil,
          :channel => String.t() | nil,
          :source => ContifyAPI.Model.Source.t() | nil
        }
end

defimpl Poison.Decoder, for: ContifyAPI.Model.Duplicate do
  import ContifyAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:source, :struct, ContifyAPI.Model.Source, options)
  end
end
