# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ContifyAPI.Model.Error do
  @moduledoc """
  Describes the error in detail.
  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :message,
    :fields
  ]

  @type t :: %__MODULE__{
          :code => integer() | nil,
          :message => String.t() | nil,
          :fields => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ContifyAPI.Model.Error do
  def decode(value, _options) do
    value
  end
end
