# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ContifyAPI.Model.Insight do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :title,
    :summary,
    :url,
    :pub_date,
    :image_url,
    :channel,
    :language,
    :previews,
    :duplicates,
    :attachments,
    :source,
    :companies,
    :industries,
    :topics,
    :custom_topics,
    :locations,
    :content_types
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :title => String.t() | nil,
          :summary => String.t() | nil,
          :url => String.t() | nil,
          :pub_date => DateTime.t() | nil,
          :image_url => String.t() | nil,
          :channel => String.t() | nil,
          :language => ContifyAPI.Model.Language.t() | nil,
          :previews => [ContifyAPI.Model.Preview.t()] | nil,
          :duplicates => [ContifyAPI.Model.Duplicate.t()] | nil,
          :attachments => [ContifyAPI.Model.Attachment.t()] | nil,
          :source => ContifyAPI.Model.Source.t() | nil,
          :companies => [ContifyAPI.Model.InsightCompany.t()] | nil,
          :industries => [ContifyAPI.Model.Tags.t()] | nil,
          :topics => [ContifyAPI.Model.Tags.t()] | nil,
          :custom_topics => [ContifyAPI.Model.Tags.t()] | nil,
          :locations => [ContifyAPI.Model.Tags.t()] | nil,
          :content_types => [ContifyAPI.Model.Tags.t()] | nil
        }
end

defimpl Poison.Decoder, for: ContifyAPI.Model.Insight do
  import ContifyAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:language, :struct, ContifyAPI.Model.Language, options)
    |> deserialize(:previews, :list, ContifyAPI.Model.Preview, options)
    |> deserialize(:duplicates, :list, ContifyAPI.Model.Duplicate, options)
    |> deserialize(:attachments, :list, ContifyAPI.Model.Attachment, options)
    |> deserialize(:source, :struct, ContifyAPI.Model.Source, options)
    |> deserialize(:companies, :list, ContifyAPI.Model.InsightCompany, options)
    |> deserialize(:industries, :list, ContifyAPI.Model.Tags, options)
    |> deserialize(:topics, :list, ContifyAPI.Model.Tags, options)
    |> deserialize(:custom_topics, :list, ContifyAPI.Model.Tags, options)
    |> deserialize(:locations, :list, ContifyAPI.Model.Tags, options)
    |> deserialize(:content_types, :list, ContifyAPI.Model.Tags, options)
  end
end
