# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ContifyAPI.Model.InsightCompany do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :logo,
    :url
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :logo => String.t() | nil,
          :url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ContifyAPI.Model.InsightCompany do
  def decode(value, _options) do
    value
  end
end
