# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ContifyAPI.Model.InsightsResponse do
  @moduledoc """
  This object contains one page of Insights against applied filters.
  """

  @derive [Poison.Encoder]
  defstruct [
    :results,
    :count,
    :next,
    :previous
  ]

  @type t :: %__MODULE__{
          :results => [ContifyAPI.Model.Insight.t()] | nil,
          :count => integer() | nil,
          :next => String.t() | nil,
          :previous => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ContifyAPI.Model.InsightsResponse do
  import ContifyAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:results, :list, ContifyAPI.Model.Insight, options)
  end
end
