# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ContifyAPI.Model.Language do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ContifyAPI.Model.Language do
  def decode(value, _options) do
    value
  end
end
