# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ContifyAPI.Model.Preview do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :url,
    :title,
    :summary
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :url => String.t() | nil,
          :title => String.t() | nil,
          :summary => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ContifyAPI.Model.Preview do
  def decode(value, _options) do
    value
  end
end
