# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ContifyAPI.Api.Location do
  @moduledoc """
  API calls for all endpoints tagged `Location`.
  """

  alias ContifyAPI.Connection
  import ContifyAPI.RequestBuilder

  @doc """
  Search for a Location
  Use the Search location end-point to fetch a list of locations  against a query string. The elements in the locations list contain an ID value along with additional information like location name. for each loaction

  ### Parameters

  - `connection` (ContifyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:name` (String.t): Name of the location to search
    - `:page` (integer()): Use this to paginate through the list

  ### Returns

  - `{:ok, ContifyAPI.Model.SearchLocationGet200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec search_location_get(Tesla.Env.client(), keyword()) ::
          {:ok, ContifyAPI.Model.Error.t()}
          | {:ok, ContifyAPI.Model.SearchLocationGet200Response.t()}
          | {:ok, String.t()}
          | {:error, Tesla.Env.t()}
  def search_location_get(connection, opts \\ []) do
    optional_params = %{
      :name => :query,
      :page => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/search-location")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %ContifyAPI.Model.SearchLocationGet200Response{}},
      {400, %ContifyAPI.Model.Error{}},
      {403, false},
      {404, %ContifyAPI.Model.Error{}},
      {405, %ContifyAPI.Model.Error{}},
      {500, %ContifyAPI.Model.Error{}},
      {503, false}
    ])
  end
end
